# Generated by Django 5.2.5 on 2026-04-23 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('habilidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
                'db_table': 'Habilidad',
            },
        ),
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('trofeo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_trofeo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono_trofeo', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Trofeos',
                'db_table': 'Trofeo',
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('mision_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('instrucciones_polya', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('tipo_operacion', models.CharField(choices=[('suma', 'Suma'), ('resta', 'Resta'), ('multiplicacion', 'Multiplicación'), ('division', 'División')], max_length=20)),
                ('alternativa1', models.CharField(db_column='alternativa1', max_length=50, verbose_name='Alternativa 1')),
                ('alternativa2', models.CharField(db_column='alternativa2', max_length=50, verbose_name='Alternativa 2')),
                ('alternativa3', models.CharField(db_column='alternativa3', max_length=50, verbose_name='Alternativa 3')),
                ('solucion_correcta', models.CharField(db_column='solucion_correcta', max_length=50, verbose_name='Solución Correcta')),
                ('habilidad', models.ForeignKey(db_column='habilidad_id', on_delete=django.db.models.deletion.CASCADE, to='misiones.habilidad')),
            ],
            options={
                'verbose_name_plural': 'Misiones',
                'db_table': 'Mision',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='IntentoMision',
            fields=[
                ('intento_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('rechazado', 'Incorrecto'), ('en_progreso', 'En Progreso')], max_length=20)),
                ('solucion_propuesta', models.TextField(blank=True, null=True)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mision', models.ForeignKey(db_column='mision_id', on_delete=django.db.models.deletion.CASCADE, to='misiones.mision')),
            ],
            options={
                'verbose_name_plural': 'Intentos de Misiones',
                'db_table': 'Intento_Mision',
                'ordering': ['-fecha_intento'],
            },
        ),
        migrations.CreateModel(
            name='PolyaTrabajoUM',
            fields=[
                ('id', models.AutoField(db_column='polya_um_id', primary_key=True, serialize=False)),
                ('que_se_pide', models.TextField(blank=True, null=True)),
                ('datos_conocidos', models.TextField(blank=True, null=True)),
                ('incognitas', models.TextField(blank=True, null=True)),
                ('representacion', models.CharField(blank=True, max_length=500, null=True)),
                ('estrategia_principal', models.TextField(blank=True, null=True)),
                ('tactica_similar', models.BooleanField(default=False)),
                ('tactica_descomponer', models.BooleanField(default=False)),
                ('tactica_ecuaciones', models.BooleanField(default=False)),
                ('tactica_formula', models.BooleanField(default=False)),
                ('desarrollo', models.TextField(blank=True, null=True)),
                ('resultados_intermedios', models.TextField(blank=True, null=True)),
                ('revision_verificacion', models.TextField(blank=True, null=True)),
                ('comprobacion_otro_metodo', models.TextField(blank=True, null=True)),
                ('conclusion_final', models.TextField(blank=True, null=True)),
                ('confianza', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identificacion_operacion', models.TextField(blank=True, null=True)),
                ('por_que_esa_operacion', models.TextField(blank=True, null=True)),
                ('mision', models.ForeignKey(db_column='mision_id', on_delete=django.db.models.deletion.CASCADE, to='misiones.mision')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trabajos Polya (Usuario-Misión)',
                'db_table': 'Polya_Trabajo_UM',
                'unique_together': {('usuario', 'mision')},
            },
        ),
        migrations.CreateModel(
            name='Sumandos',
            fields=[
                ('sumando_id', models.AutoField(primary_key=True, serialize=False)),
                ('sumando', models.TextField(blank=True, null=True)),
                ('polya_um_id', models.ForeignKey(db_column='polya_um_id', on_delete=django.db.models.deletion.CASCADE, to='misiones.polyatrabajoum')),
            ],
            options={
                'verbose_name_plural': 'Sumandos',
                'db_table': 'Sumandos',
            },
        ),
        migrations.CreateModel(
            name='ProgresoHabilidad',
            fields=[
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('porcentaje_avance', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('habilidad', models.OneToOneField(db_column='habilidad_id', on_delete=django.db.models.deletion.CASCADE, to='misiones.habilidad')),
            ],
            options={
                'verbose_name_plural': 'Progreso de Habilidades',
                'db_table': 'Progreso_Habilidad',
                'unique_together': {('usuario', 'habilidad')},
            },
        ),
        migrations.CreateModel(
            name='TrofeoEstudiante',
            fields=[
                ('trofeo', models.OneToOneField(db_column='trofeo_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='misiones.trofeo')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trofeos de Estudiantes',
                'db_table': 'Trofeo_Estudiante',
                'unique_together': {('trofeo', 'usuario')},
            },
        ),
    ]
