# Generated by Django 5.2.5 on 2026-05-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentomision',
            name='intentos_fallidos',
            field=models.IntegerField(default=0, help_text='Cantidad de veces que el alumno envió una respuesta incorrecta antes de acertar.'),
        ),
        migrations.AddField(
            model_name='intentomision',
            name='tiempo_total_segundos',
            field=models.IntegerField(default=0, help_text='Tiempo total invertido en la misión entera.'),
        ),
        migrations.AddField(
            model_name='mision',
            name='nivel_dificultad',
            field=models.CharField(choices=[('1', 'Fácil'), ('2', 'Medio'), ('3', 'Difícil')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='polyatrabajoum',
            name='tiempo_fase_1_segundos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polyatrabajoum',
            name='tiempo_fase_2_segundos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polyatrabajoum',
            name='tiempo_fase_3_segundos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polyatrabajoum',
            name='tiempo_fase_4_segundos',
            field=models.IntegerField(default=0),
        ),
    ]
