# Generated by Django 5.2.5 on 2026-05-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misiones', '0002_intentomision_intentos_fallidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresohabilidad',
            name='nivel_actual',
            field=models.CharField(choices=[('1', 'Fácil'), ('2', 'Medio'), ('3', 'Difícil')], default='1', max_length=10),
        ),
    ]
