# Generated by Django 5.2.5 on 2026-05-16 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misiones', '0003_progresohabilidad_nivel_actual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "Progreso_Habilidad" DROP CONSTRAINT IF EXISTS "Progreso_Habilidad_pkey" CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            'ALTER TABLE "Trofeo_Estudiante" DROP CONSTRAINT IF EXISTS "Trofeo_Estudiante_pkey" CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AddField(
            model_name='progresohabilidad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='trofeoestudiante',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='progresohabilidad',
            name='habilidad',
            field=models.ForeignKey(db_column='habilidad_id', on_delete=django.db.models.deletion.CASCADE, to='misiones.habilidad'),
        ),
        migrations.AlterField(
            model_name='progresohabilidad',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trofeoestudiante',
            name='trofeo',
            field=models.ForeignKey(db_column='trofeo_id', on_delete=django.db.models.deletion.CASCADE, to='misiones.trofeo'),
        ),
    ]
