# Generated by Django 5.2.5 on 2026-04-23 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('biblioteca_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(db_column='Descripcion', verbose_name='Descripción')),
                ('solucion', models.TextField(db_column='Solucion', verbose_name='Solución')),
                ('tipo', models.CharField(choices=[('Practica', 'Practica'), ('Juego', 'Juego'), ('Contenido', 'Contenido')], db_column='tipo', max_length=50, verbose_name='Tipo')),
                ('activo', models.BooleanField(db_column='activo', default=True, verbose_name='Activo')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenido de Biblioteca',
                'verbose_name_plural': 'Contenidos de Biblioteca',
                'db_table': 'Biblioteca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Biblioteca_Contenido',
            fields=[
                ('biblioteca_contenido_id', models.AutoField(primary_key=True, serialize=False)),
                ('teoria', models.TextField(db_column='teoria', verbose_name='Teoria')),
                ('pasos_trucos', models.TextField(db_column='pasos_trucos', verbose_name='Pasos y Trucos')),
                ('ejemplo', models.TextField(db_column='ejemplo', verbose_name='Ejemplo')),
                ('tipo', models.TextField(db_column='tipo', verbose_name='Tipo')),
                ('biblioteca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_contenido', to='biblioteca.biblioteca')),
            ],
            options={
                'verbose_name': 'Contenido de Biblioteca',
                'verbose_name_plural': 'Contenidos de Biblioteca',
                'db_table': 'Biblioteca_Contenido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PolyaBiblioteca',
            fields=[
                ('id', models.AutoField(db_column='polya_biblioteca_id', primary_key=True, serialize=False)),
                ('identificacion_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('por_que_esa_operacion', models.CharField(blank=True, max_length=300, null=True)),
                ('que_se_pide', models.TextField(blank=True, null=True)),
                ('datos_conocidos', models.TextField(blank=True, null=True)),
                ('incognitas', models.TextField(blank=True, null=True)),
                ('representacion', models.CharField(blank=True, max_length=500, null=True)),
                ('estrategia_principal', models.TextField(blank=True, null=True)),
                ('desarrollo', models.TextField(blank=True, null=True)),
                ('resultados_intermedios', models.TextField(blank=True, null=True)),
                ('revision_verificacion', models.TextField(blank=True, null=True)),
                ('comprobacion_otro_metodo', models.TextField(blank=True, null=True)),
                ('conclusion_final', models.TextField(blank=True, null=True)),
                ('confianza', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biblioteca', models.ForeignKey(db_column='biblioteca_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajo Polya (Biblioteca)',
                'verbose_name_plural': 'Trabajos Polya (Biblioteca)',
                'db_table': 'Polya_Biblioteca',
                'managed': True,
                'unique_together': {('usuario', 'biblioteca')},
            },
        ),
        migrations.CreateModel(
            name='Sumandos_Biblioteca',
            fields=[
                ('sumando_id', models.AutoField(primary_key=True, serialize=False)),
                ('sumando', models.TextField(blank=True, null=True)),
                ('polya_biblioteca', models.ForeignKey(db_column='polya_biblioteca_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.polyabiblioteca')),
            ],
            options={
                'verbose_name': 'Sumando (Biblioteca)',
                'verbose_name_plural': 'Sumandos (Biblioteca)',
                'db_table': 'Sumandos_Biblioteca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Biblioteca_Usuario',
            fields=[
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('estado', models.BooleanField(db_column='estado', default=True, verbose_name='Estado')),
                ('biblioteca', models.ForeignKey(db_column='biblioteca_id', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca')),
            ],
            options={
                'verbose_name': 'Estado de Biblioteca',
                'verbose_name_plural': 'Estados de Biblioteca',
                'db_table': 'Biblioteca_Usuario',
                'managed': True,
                'unique_together': {('usuario', 'biblioteca')},
            },
        ),
    ]
