# Generated by Django 5.2.5 on 2026-04-23 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('contraseña_hash', models.CharField(max_length=128)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=100)),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Auditoria_Usuario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.rol'),
        ),
    ]
